---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/posts/{post_id}/comments":
    parameters:
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    get:
      summary: list comments
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
  "/api/posts":
    get:
      summary: list posts
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
        '401':
          description: authentication failed
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
